version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        volumes:
            - ./:/var/www/html
            - ./database:/var/www/html/database
        working_dir: /var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel
        depends_on:
            - nginx

    nginx:
        image: nginx:stable
        container_name: laravel_nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
